### PR TITLE
Added a TestFixture constructor for ITestOutputHelper.

### PR DESCRIPTION
**Pull request by xxAtrain223**
Added a `TestFixture` constructor for `ITestOutputHelper` so that `TestFixture` can be used in a [SpecFlow XUnit](https://docs.specflow.org/projects/specflow/en/latest/Integrations/xUnit.html) project.

### CODE REVIEW

**Comment by xxAtrain223** [comment]
I'm still trying to figure out how to write tests for this addition. I'm struggling with how to inject an `ITestOutputHelper` mock.

**Comment by dj-nitehawk** [comment]
why can't you just do the following in your derived fixture?
```cs
public class MyFixture(IMessageSink s, ITestOutputHelper h) : TestFixture<Program>(s)
{
    protected override void ConfigureApp(IWebHostBuilder a)
    {
        a.ConfigureLogging(l => l.ClearProviders().AddXUnit(h));
    }
}
```

**Comment by xxAtrain223** [comment]
SpecFlow uses BoDi for dependency injection, the SpecFlow XUnit plugin doesn't have IMessageSink registered. So when I try to run a test with the Fixture injected, I get the following exception:

```
  Message:
System.AggregateException : One or more errors occurred. (Interface cannot be resolved: Xunit.Abstractions.IMessageSink) (The following constructor parameters did not have matching fixture data: TestProject_XUnitAssemblyFixture assemblyFixture)
---- BoDi.ObjectContainerException : Interface cannot be resolved: Xunit.Abstractions.IMessageSink
---- The following constructor parameters did not have matching fixture data: TestProject_XUnitAssemblyFixture assemblyFixture

  Stack Trace:
----- Inner Stack Trace #1 (BoDi.ObjectContainerException) -----
TestExecutionEngine.FireEvents(HookType hookType)
TestExecutionEngine.OnTestRunStart()
TestRunner.OnTestRunStart()
TestRunnerManager.FireTestRunStart()
TestRunnerManager.OnTestRunStart(Assembly testAssembly, IContainerBuilder containerBuilder)
StarPromiseDateRecalculator_Specs_XUnitAssemblyFixture.ctor() line 19
RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

The SpecFlow XUnit plugin does have the `ITestOutputHelper` registered and since the `MartinCostello.Logging.XUnit` package has a `AddXUnit` overload for `ITestOutputHelper`, I thought it would be easier and faster to add a `TestFixture` overload for `ITestOutputHelper` than adding `IMessageSink` to the SpecFlow XUnit plugin code generation.

I also thought this could help other users where they have `ITestOutputHelper` and not `IMessageSink`.

**Comment by dj-nitehawk** [comment]
available in `v5.20.0.2-beta`

**Comment by xxAtrain223** [comment]
Thank you!

________________________________

**Pull request merged**
