### PR TITLE
prevent caching the HandlerExecutor method

### PR DESCRIPTION
**Pull request by WahidBitar**
prevent caching the HandlerExecutor method to not use the cached resolved services.

related to [this issue](https://github.com/FastEndpoints/FastEndpoints/issues/324)

https://discord.com/channels/933662816458645504/1039086761302818856

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
we're gonna need to find an alternative because `handlerType.HandlerExecutor(tCommand, handler)` is going to compile the expression on each call. that's why it was cached, so the compilation only happens once.

i'm investigating now. let's see...

**Comment by WahidBitar** [comment]
I've figured it out for the commands without result
`return ((ICommandHandler<TCommand>)handler).ExecuteAsync(command, ct);`
but still have some difficulties with the `ICommand<>`

**Comment by dj-nitehawk** [comment]
i'm trying to get the compiled expression to create an instance of the handler on each execution. something like this but it's currently not working. maybe you can see whats wrong?
```cs
    private static Func<object, CancellationToken, Task<TResult>> HandlerExecutor<TResult>(this Type tHandler, Type tCommand, object handler)
    {
        //object Config.ServiceResolver.CreateInstance(tHandler)

        //Task<TResult> ExecuteAsync((TCommand)cmd, ct);

        var resolverInstance = Expression.Constant(Config.ServiceResolver);
        var typeParam = Expression.Parameter(typeof(Type), "handlerType");
        var serviceProviderParam = Expression.Parameter(typeof(IServiceProvider), "tServiceProvider");
        var createInstanceMethod = typeof(IServiceResolver).GetMethod("CreateInstance", BindingFlags.Instance | BindingFlags.Public | BindingFlags.FlattenHierarchy)!;
        var createInstanceCall = Expression.Call(resolverInstance, createInstanceMethod, typeParam, serviceProviderParam);
        var convertedInstance = Expression.Convert(createInstanceCall, tHandler);

        var execMethod = tHandler.GetMethod("ExecuteAsync", BindingFlags.Instance | BindingFlags.Public | BindingFlags.FlattenHierarchy)!;
        var cmdParam = Expression.Parameter(Types.Object, "cmd");
        var ctParam = Expression.Parameter(typeof(CancellationToken), "ct");
        var methodCall = Expression.Call(convertedInstance, execMethod, Expression.Convert(cmdParam, tCommand), ctParam);

        var xx = Expression.Lambda<Func<object, CancellationToken, Task<TResult>>>(
            methodCall,
            cmdParam,
            ctParam
        );
        var yy = xx.ToString();
        return xx.Compile();

        //.Compile();
    }
```
this bloody expressions api is a bloody nightmare to work with.

**Comment by WahidBitar** [comment]
I'm not totally sure, but I guess it is creating an instance of a handler each time, but the problem is the HandlerExecutor method keeps the reference to the very first instance
```
var handler = Config.ServiceResolver.CreateInstance(def.HandlerType); // this is working right
def.ExecuteMethod ??= def.HandlerType.HandlerExecutor(tCommand, handler); // will compile the executor just for the first time
return ((Func<object, CancellationToken, Task>)def.ExecuteMethod)(command, CT); // but here we're not passing anything related to the new resolved handler
```

**Pull request closed without merging**
