### PR TITLE
inner Validater support both DataAnnotation AND FluentValidation

### PR DESCRIPTION
**Pull request by vipwan**
#499

### CODE REVIEW

**Comment by vipwan** [comment]
#501

**Comment by dj-nitehawk** [comment]
this looks good. can you please add an integration test to cover the newly added endpoint?
thanks!

**Comment by dj-nitehawk** [comment]
this is ready to be merged once test coverage is added ;-)

**Comment by vipwan** [comment]
#508

**Comment by vipwan** [comment]
> this is ready to be merged once test coverage is added ;-)

test done

**Comment by dj-nitehawk** [comment]
@vipwan i've changed the feature to be off by default. you'll have to turn it on if you wanna use it.
```cs
app.UseFastEndpoints(c.Validation.EnableDataAnnotationsSupport = true;)
```
because it's going to allocate some memory and goes through the MSDA validation path even when the dtos are not decorated with MSDA attributes.

**Pull request merged**
