### PR TITLE
Introducing FastEndpoints Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [FastEndpoints Guru](https://gurubase.io/g/fastendpoints) to Gurubase. FastEndpoints Guru uses the data from this repo and data from the [docs](https://fast-endpoints.com) to answer questions by leveraging the LLM.

In this PR, I showcased the "FastEndpoints Guru", which highlights that FastEndpoints now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable FastEndpoints Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
hey...
that's awesome.
i've changed the styling a bit to fit with the other icons.
let me know if that's ok and i'll merge.
btw, how often is the LLM retrained with new information?
thanks!

**Comment by kursataktas** [comment]
Hey @dj-nitehawk, thanks for the review!

> i've changed the styling a bit to fit with the other icons.
let me know if that's ok and i'll merge.

Looks good to me.

> btw, how often is the LLM retrained with new information?

I will watch the repository to get notified of updates and then update the sources accordingly. Additionally, we will release an admin panel that will allow repository maintainers to manage their Gurus. I’ll update you once it’s available, so you will have full control over it.

**Comment by kursataktas** [comment]
Hi @dj-nitehawk,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by dj-nitehawk** [comment]
claim request submitted.
thank you very much.
btw, just out of curiosity, what kind of hardware is the guru service running on?

**Comment by kursataktas** [comment]
Great, I assigned it 👍 

If I’m not misunderstanding, all services run on GCP. However, if you’re asking about something more specific, please let me know.

**Comment by dj-nitehawk** [comment]
ah i see. i though you guys are running your own baremetal servers :-)
all good...

**Comment by kursataktas** [comment]
Hello @dj-nitehawk,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by dj-nitehawk** [comment]
thank you... 
i've [added the widget](https://github.com/FastEndpoints/Documentation/blob/533b48cc4f9b4e98fde74df26ff1ecfd242faa5d/src/app.html#L26-L32) to the site.
it'll go live in the next release at the end of this month.

**Comment by kursataktas** [comment]
Hey @dj-nitehawk,

I wanted to update you that we’ve released the Gurubase GitHub bot.
This means you can now integrate your Guru into your repository,  so users can ask it questions directly through GitHub issues. By default, the Gurubase bot automatically responds to newly opened issues, but you can customize its behavior if needed.

You can see it in action in [this demo issue](https://github.com/Gurubase/gurubase/issues/248).
More information about the bot can be found [here](https://docs.gurubase.ai/integrations/github-bot).

gurubase-github-bot-demo

-----

_Note: As I mentioned in my first update on this thread, please let me know if you’d prefer not to receive updates here._

**Pull request merged**
