### PR TITLE
Add GlobalPre/PostProcessors and integration/unit test amendment

### PR DESCRIPTION
**Pull request by rudiv**
This adds a  `GlobalPreProcessor` and `GlobalPostProcessor` class to support state-driven global processors.

The existing unit/integration tests were hijacked as the change is relatively straightforward and related, though they could be separated if needed?

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
#518 was merged to master and it seems to have broken your PR.
bunch of tests are failing.
would you be able to sort that out pls?

**Comment by rudiv** [comment]
Tests are fixed, but I'm more curious as to why it didn't (after fixing it to just inherit from `PostProcessor<object, TState>`).

I know #518 was marked as a breaking change but it's a potentially serious breaking change for anyone using `object` as the `TRequest` as that doesn't seem to work any more. Instead, the typeless `IPre/PostProcessor` has to be used.

**Comment by rudiv** [comment]
Hmmm yes this is the underlying error now:

> Unable to cast object of type 'FastEndpoints.PreProcessorContext`1[FastEndpoints.EmptyRequest]' to type 'FastEndpoints.IPreProcessorContext`1[System.Object]'.

I believe it's due to the fact that `EmptyRequest` is a struct. Changing it to a class makes everything pass again. Given that's the case, I'm not sure why this is only coming up after the merge.

**Comment by dj-nitehawk** [comment]
just tried this PR branch with the following and things seem to be working ok:
```cs
app.UseFastEndpoints(
       x => x.Endpoints.Configurator = ep =>
       {
           ep.PreProcessors(Order.Before, new GlobalPreProc());
       });
       
class GlobalPreProc : GlobalPreProcessor<ProcState>
{
    public override Task PreProcessAsync(IPreProcessorContext ctx, ProcState state, CancellationToken ct)
    {
        state.Id = 100;

        return Task.CompletedTask;
    }
}

class ProcState
{
    public int Id { get; set; }
}

sealed class MyEndpoint : Endpoint<EmptyRequest>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(EmptyRequest r, CancellationToken c)
    {
        var procState = ProcessorState<ProcState>();
        await SendAsync(procState.Id);
    }
}
```

i'm not seeing any invalid cast exceptions. can you update the above code and send back to replicate what you're seeing?

cheers!

**Comment by rudiv** [comment]
No, everything is fine in what I pushed. I added the methods in to the abstract class (rather than inheriting from `PostProcessor<object, TState>` as it did before).

Previously, this was possible (modifying your code):
```cs
class GlobalPreProc : PreProcessor<object, ProcState>, IGlobalPreProcessor
{
    public override Task PreProcessAsync(IPreProcessorContext<object> ctx, ProcState state, CancellationToken ct)
    {
        state.Id = 100;

        return Task.CompletedTask;
    }
}
```

After the change, it's not and you will get the cast error.

**Comment by dj-nitehawk** [comment]
ah got it...
so i believe this is ready to be merged then?
looks all good to my eyes.

**Comment by rudiv** [comment]
Good for me!

**Comment by dj-nitehawk** [comment]
done!
appreciate the contribution 🙏🙏🙏

**Pull request merged**
