### PR TITLE
Public configuration getters

### PR DESCRIPTION
**Pull request by gius**
Make configuration getters and EndpointSummary public to allow custom OperationProcessors based on the original source code.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
this info is already exposed via the `EndpointDefinition` which you can obtain like so:
https://github.com/FastEndpoints/FastEndpoints/blob/60c171af30fcd357cbf06e975d7e290cb92146e3/Src/Swagger/OperationProcessor.cs#L48-L49

use extension method `ctx.GetEndpointDefinition()` which is available in `v5.3.1.3-beta`

**Comment by gius** [comment]
Thank you for your answer. I am sorry, I probably don't get it - let's say you want to copy the OperationProcessor, how do you replace these rows https://github.com/FastEndpoints/FastEndpoints/blob/60c171af30fcd357cbf06e975d7e290cb92146e3/Src/Swagger/OperationProcessor.cs#L58-L59 as `Config.VerOpts.Prefix` and `Config.EpOpts.RoutePrefix` are internal?

The same holds for https://github.com/FastEndpoints/FastEndpoints/blob/60c171af30fcd357cbf06e975d7e290cb92146e3/Src/Swagger/OperationProcessor.cs#L103 and `ProducesResponseTypeMetadata.Example`.

**Comment by dj-nitehawk** [comment]
ah my bad. it is now sorted in `v5.3.1.4-beta`
https://github.com/FastEndpoints/FastEndpoints/blob/d8a4c171cceba2e1541e9622df93720d4a138803/Src/Swagger/OperationProcessor.cs#L58-L59
and
https://github.com/FastEndpoints/FastEndpoints/blob/d8a4c171cceba2e1541e9622df93720d4a138803/Src/Swagger/OperationProcessor.cs#L103

because i'd prefer to keep the config properties setter only.

**Comment by gius** [comment]
Thank you!

**Pull request closed without merging**
