### PR TITLE
Adds an overload to SendAsync which will accept an object (as long as…

### PR DESCRIPTION
**Pull request by kcadduk**
… it is not of the typed TResponse type).

It will check to see if an IResponseInterceptor has been provided to the Definition of the endpoint, and if it has, run that code.

Then it checks to see if a response has started, if it has, it will simply return, or if not, it will run the SendAsync extension of HttpContext as normal.

Please note: I cannot seem to find the docs to add this information, if you need that too, let me know.

### CODE REVIEW

**Comment by dj-nitehawk** [comment]
looks like we need to call the method `SendInterceptedAsync()` because one of the existing unit tests was failing due to ambiguity between the new send method and the existing generic send method when the endpoints response type is set at `object`.
hope this is ok...

**Comment by kcadduk** [comment]
> looks like we need to call the method `SendInterceptedAsync()` because one of the existing unit tests was failing due to ambiguity between the new send method and the existing generic send method when the endpoint's response type is set as `object`. hope this is ok...

I'm fine with the syntax. One thing that I might change, but i'll wait for your input on this first. Is that if we now have a specific method, i'd like to throw an exception if the interceptor hasn't been set. 

I'm not a fan or arbitrarily blowing up the code when it doesn't need to, but also, I'm not a fan of silently calling SendAsync because they forgot to set an interceptor. Before, interceptors were a part of SendAsync, so an interceptor not being set was kind of okay, but I have a difference of opinion now it has its own SendX terminology. What are your thoughts?

Thanks
Kevin

**Comment by dj-nitehawk** [comment]
yep good idea... go for it...

**Comment by kcadduk** [comment]
Done, I also passed the statusCode into the interface method too. It should have done that from the beginning.

**Pull request merged**
